name: CI

on:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]

jobs:
  test-earliest:
    name: Run test suite on the earliest supported Python version
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
        with:
          fetch-depth: 1
          submodules: 'recursive'
      - uses: actions/setup-python@v5
        id: earliest
        with:
          python-version: '3.7.x'
          check-latest: true
          cache: 'pip'
          cache-dependency-path: '**/requirements-earliest.txt'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r .github/requirements-earliest.txt

      - name: Report selected versions
        run: |
          echo Selected '${{ steps.earliest.outputs.python-version }}'
          ./hg-fast-export.sh --debug

      - name: Run tests on earliest supported Python version
        run: make -C t

  test-latest:
    name: Run test suite on the latest supported python version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
        with:
          fetch-depth: 1
          submodules: 'recursive'
      - uses: actions/setup-python@v5
        id: latest
        with:
          python-version: '3.x'
          check-latest: true
          cache: 'pip'
          cache-dependency-path: '**/requirements-latest.txt'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r .github/requirements-latest.txt

      - name: Report selected version
        run: |
          echo Selected '${{ steps.latest.outputs.python-version }}'
          ./hg-fast-export.sh --debug

      - name: Run tests on 3.x
        run: make -C t
